apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: frontend
    spec:
      containers:
      - image: grafana-img
        name: grafana
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
        - containerPort: 3000
          name: grafana