apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
    tier: frontend
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin-img
        name: phpmyadmin
        imagePullPolicy: Never
        securityContext:
          privileged: true
        livenessProbe:
          exec:
            command:
              - bin/sh
              - -c
              - ./liveness.sh
          initialDelaySeconds: 15
          periodSeconds: 10
        ports:
        - containerPort: 5000
          name: phpmyadmin
        env:
          - name: PMA_HOST
            value: mysql
          - name: PMA_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password