apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
  - name: ftp-server
    protocol: TCP
    port: 21
    nodePort: 21
  - name: ftp-data
    protocol: TCP
    port: 20
    nodePort: 20
  - name: ftp-pass1
    protocol: TCP
    port: 30032
    nodePort: 30032
  - name: ftp-pass2
    protocol: TCP
    port: 30033
    nodePort: 30033
  - name: ftp-pass3
    protocol: TCP
    port: 30034
    nodePort: 30034
  selector:
    app: ftps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
        tier: frontend
    spec:
      containers:
      - image: ftps-img
        name: ftps
        imagePullPolicy: Never
        securityContext:
          privileged: true
        livenessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - ./liveness.sh
          initialDelaySeconds: 15
          periodSeconds: 10
        ports:
        - containerPort: 21
          name: ftp-server
        - containerPort: 20
          name: ftp-data
        - containerPort: 30032
          name: ftp-pass1
        - containerPort: 30033
          name: ftp-pass2
        - containerPort: 30034
          name: ftp-pass3
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home/ftp_user
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim